#!/bin/bash
# Enable the Backupscript

AUTOSTARTDIR="/home/$USER/.config/autostart/"
AUTOSTARTFILE=${AUTOSTARTDIR}bakeup.desktop

if [ "$1" == "--enable" ]; then
	# Enable
	pushd . > /dev/null
	SCRIPT_PATH="${BASH_SOURCE[0]}";
	while([ -h "${SCRIPT_PATH}" ]); do
	    cd "`dirname "${SCRIPT_PATH}"`"
	    SCRIPT_PATH="$(readlink "`basename "${SCRIPT_PATH}"`")";
	done
	cd "`dirname "${SCRIPT_PATH}"`" > /dev/null
	SCRIPT_PATH="`pwd`";
	popd  > /dev/null
	SCRIPTDIR=$SCRIPT_PATH

	if [ -d "/home/$USER/.config/autostart/" ]; then
		echo "Create Autostart entry"
		
		echo "[Desktop Entry]" > $AUTOSTARTFILE
		echo "Type=Application" >> $AUTOSTARTFILE
		echo "Exec=$SCRIPTDIR/bakeupd" >> $AUTOSTARTFILE
		echo "Terminal=false" >> $AUTOSTARTFILE
		echo "Icon=security-high" >> $AUTOSTARTFILE
		echo "Name=BakeUp your System" >> $AUTOSTARTFILE
	elif [ -e "/home/$USER/.config/openbox/autostart" ]; then
		zenity --question --title='BakeUp' --text="You are running Openbox.\nBakeUp will add a line to your autostart file\nThis could not be undo\nProceed?"
		if [ "$?" == "0" ]; then
			echo "$SCRIPTDIR/bakeupd" >> "/home/$USER/.config/openbox/autostart"
		fi
	else
		zenity --info --title='BakeUp' --text="Could not add the script to autorun.\nPlease do this step by hand"
	fi


	exit 0
fi

if [ "$1" == "--disable" ]; then
	# Disable

	echo "Remove Autostart Entry"
	rm $AUTOSTARTFILE

fi