#!/bin/bash

if [ "$1" == "--install" ]; then

	pushd . > /dev/null
	SCRIPT_PATH="${BASH_SOURCE[0]}";
	while([ -h "${SCRIPT_PATH}" ]); do
	    cd "`dirname "${SCRIPT_PATH}"`"
	    SCRIPT_PATH="$(readlink "`basename "${SCRIPT_PATH}"`")";
	done
	cd "`dirname "${SCRIPT_PATH}"`" > /dev/null
	SCRIPT_PATH="`pwd`";
	popd  > /dev/null
	SCRIPTDIR=$SCRIPT_PATH

	mkdir /opt/bakeup/
	cp ${SCRIPTDIR}/bakeup /opt/bakeup/
	cp ${SCRIPTDIR}/bakeup-change-disk /opt/bakeup/
	cp ${SCRIPTDIR}/bakeup-enable /opt/bakeup/
	cp ${SCRIPTDIR}/bakeup-plan /opt/bakeup/
	cp ${SCRIPTDIR}/bakeup-create-plan /opt/bakeup/
	cp ${SCRIPTDIR}/bakeupd /opt/bakeup/
	chmod -R a+x /opt/bakeup/

	DESKTOPFILE='/usr/share/applications/bakeup.desktop'
	echo "[Desktop Entry]" > $DESKTOPFILE
	echo "Type=Application" >> $DESKTOPFILE
	echo "Exec=/opt/bakeup/bakeup" >> $DESKTOPFILE
	echo "Terminal=false" >> $DESKTOPFILE
	echo "Icon=security-high" >> $DESKTOPFILE
	echo "Name=BakeUp" >> $DESKTOPFILE
	echo "Categories=System;" >> $DESKTOPFILE

	zenity --info --title='BakeUp' --text="installation successful!"
	exit
fi

zenity --question --title='BakeUp' --text="Hello and Welcome to BakeUp!\n\nThis Setup will guide you through the installation of BakeUp\nProceed?"

if [ "$?" == "0" ]; then

	pushd . > /dev/null
	SCRIPT_PATH="${BASH_SOURCE[0]}";
	while([ -h "${SCRIPT_PATH}" ]); do
	    cd "`dirname "${SCRIPT_PATH}"`"
	    SCRIPT_PATH="$(readlink "`basename "${SCRIPT_PATH}"`")";
	done
	cd "`dirname "${SCRIPT_PATH}"`" > /dev/null
	SCRIPT_PATH="`pwd`";
	popd  > /dev/null
	SCRIPTDIR=$SCRIPT_PATH

	if [ -x '/usr/bin/kdesudo' ]; then
		kdesudo "$SCRIPTDIR/setup --install"
	elif [ -x '/usr/bin/gksudo' ]; then
		gksudo "$SCRIPTDIR/setup --install"
	else
		zenity --info --title='BakeUp' --text='Please run sudo setup --install in this directory'
		exit
	fi

	zenity --question --title='BakeUp' --text='Would you like to configure a backup for your home directory?'

	if [ "$?" == "0" ]; then

		sleep 1
		# Set Disk
		mkdir -p /home/$USER/.bakeup.rc/
		/opt/bakeup/bakeup-change-disk
		/opt/bakeup/bakeup-create-plan -d="$USER-Home" -s="/home/$USER/" --home
		/opt/bakeup/bakeup


	fi

fi